AWSTemplateFormatVersion: '2010-09-09'
Description: Internal NLB + API Gateway + VPC Link

Resources:

  #####################################
  # API Gateway Access Logs
  #####################################

  ApiGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/accesslogs
      RetentionInDays: 90

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  #####################################
  # NLB Access Log S3 Bucket
  #####################################

  NlbAccessLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-nlb-accesslog"
      VersioningConfiguration:
        Status: Enabled

  #####################################
  # API Gateway Log S3 Bucket
  #####################################

  ApiGatewayLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-apigw-accesslog"
      VersioningConfiguration:
        Status: Enabled

  #####################################
  # NLB Bucket Policy
  #####################################

  NlbAccessLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NlbAccessLogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:ListBucket
            Resource: !GetAtt NlbAccessLogBucket.Arn

          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub "${NlbAccessLogBucket.Arn}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  #####################################
  # Firehose IAM Role
  #####################################

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: FirehoseS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !GetAtt ApiGatewayLogBucket.Arn
                  - !Sub "${ApiGatewayLogBucket.Arn}/*"

  #####################################
  # Firehose Delivery Stream
  #####################################

  ApiGatewayLogDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "${AWS::StackName}-apigw-delivery-stream"
      DeliveryStreamType: DirectPut

      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt ApiGatewayLogBucket.Arn
        Prefix: apigateway/
        ErrorOutputPrefix: errors/
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        CompressionFormat: GZIP
        RoleARN: !GetAtt FirehoseRole.Arn

  #####################################
  # CloudWatch Logs -> Firehose Role
  #####################################

  LogsToFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com 
            Action: sts:AssumeRole

      Policies:
        - PolicyName: CWLogsToFirehose
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecordBatch
                Resource: !GetAtt ApiGatewayLogDeliveryStream.Arn

  #####################################
  # CloudWatch Logs Subscription
  #####################################

  ApiGatewayLogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn:
      - ApiGatewayAccessLogGroup
      - ApiGatewayLogDeliveryStream    
      - LogsToFirehoseRole                
      - ApiStage                         
    Properties:
      LogGroupName: !Ref ApiGatewayAccessLogGroup
      FilterPattern: ""
      DestinationArn: !Sub "arn:${AWS::Partition}:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/${AWS::StackName}-apigw-delivery-stream"
      RoleArn: !GetAtt LogsToFirehoseRole.Arn

  #####################################
  # Network Load Balancer
  #####################################

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn:
      - NlbAccessLogBucketPolicy

    Properties:
      Name: vesta-internal-nlb
      Type: network
      Scheme: internal

      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: "true"

        - Key: access_logs.s3.bucket
          Value: !Ref NlbAccessLogBucket

        - Key: access_logs.s3.prefix
          Value: nlb

      Subnets:
        - !ImportValue subnet1a-id
        - !ImportValue subnet1c-id
        - !ImportValue subnet1d-id

  #####################################
  # Target Group
  #####################################

  NlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup

    Properties:
      Name: vesta-tg
      TargetType: ip
      Protocol: TCP
      Port: 80
      VpcId: !ImportValue vpc1-id
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port

  #####################################
  # Listener
  #####################################

  NlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener

    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Protocol: TCP
      Port: 80

      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroup

  #####################################
  # API Gateway VPC Link
  #####################################

  ApiGatewayVpcLink:
    Type: AWS::ApiGateway::VpcLink

    Properties:
      Name: my-vpc-link

      TargetArns:
        - !Ref NetworkLoadBalancer

  #####################################
  # REST API
  #####################################

  RestApi:
    Type: AWS::ApiGateway::RestApi

    Properties:
      Name: MyRestApi

  #####################################
  # Proxy Resource
  #####################################

  ApiResource:
    Type: AWS::ApiGateway::Resource

    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: '{proxy+}'

  #####################################
  # Proxy Method
  #####################################

  ApiMethod:
    Type: AWS::ApiGateway::Method

    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiResource
      HttpMethod: ANY
      AuthorizationType: NONE

      RequestParameters:
        method.request.path.proxy: true

      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY

        Uri:
          Fn::Sub:
            - "http://${NlbDnsName}/{proxy}"
            - NlbDnsName: !GetAtt NetworkLoadBalancer.DNSName

        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink

        RequestParameters:
          integration.request.path.proxy: "method.request.path.proxy"

  #####################################
  # Deployment
  #####################################

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment

    DependsOn:
      - ApiMethod

    Properties:
      RestApiId: !Ref RestApi

  #####################################
  # Stage
  #####################################

  ApiStage:
    Type: AWS::ApiGateway::Stage

    DependsOn:
      - ApiGatewayAccount

    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'
