AWSTemplateFormatVersion: '2010-09-09'
Description: Internal NLB + API Gateway + VPC Link

Resources:

  #####################################
  # Network Load Balancer
  #####################################

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: vesta-internal-nlb
      Type: network
      Scheme: internal
      Subnets:
        - !ImportValue subnet1a-id
        - !ImportValue subnet1c-id
        - !ImportValue subnet1d-id

  NlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: vesta-tg
      TargetType: ip
      Protocol: TCP
      Port: 80
      VpcId: !ImportValue vpc1-id
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port

  NlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Protocol: TCP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroup

  #####################################
  # API Gateway VPC Link
  #####################################

  ApiGatewayVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: my-vpc-link
      TargetArns:
        - !Ref NetworkLoadBalancer

  #####################################
  # REST API
  #####################################

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyRestApi

  #####################################
  # Proxy Resource
  #####################################

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: '{proxy+}'

  #####################################
  # Proxy Method
  #####################################

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiResource
      HttpMethod: ANY

      AuthorizationType: NONE

      RequestParameters:
        method.request.path.proxy: true

      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET

        Uri:
          Fn::Sub:
            - 'http://${NlbDnsName}/{proxy}'
            - NlbDnsName: !GetAtt NetworkLoadBalancer.DNSName

        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink

        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'

  #####################################
  # Deployment
  #####################################

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiMethod
    Properties:
      RestApiId: !Ref RestApi

  #####################################
  # Stage
  #####################################

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod
  
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: vesta-ecs-cluster

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: vesta-taskdef

      RequiresCompatibilities:
        - FARGATE

      NetworkMode: awsvpc

      Cpu: '256'
      Memory: '512'

      ExecutionRoleArn: arn:aws:iam::473427586283:role/miyazato-kt1-account1-je-ecs-task-execution-role

      ContainerDefinitions:
        - Name: app
          Image: 473427586283.dkr.ecr.ap-northeast-1.amazonaws.com/my-nginx:latest
          Essential: true

          PortMappings:
            - ContainerPort: 80
              Protocol: tcp

  EcsServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Service Security Group

      VpcId: !ImportValue vpc1-id

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  EcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - EcsTaskDefinition
      - NlbListener

    Properties:
      ServiceName: vesta-service

      Cluster: !Ref EcsCluster

      TaskDefinition: !Ref EcsTaskDefinition

      LaunchType: FARGATE

      DesiredCount: 1

      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED

          Subnets:
            - !ImportValue subnet2a-id
            - !ImportValue subnet2c-id
            - !ImportValue subnet2d-id

          SecurityGroups:
            - !Ref EcsServiceSecurityGroup

      LoadBalancers:
        - TargetGroupArn: !Ref NlbTargetGroup
          ContainerName: app
          ContainerPort: 80


Outputs:

  NlbArn:
    Description: Network Load Balancer ARN
    Value: !Ref NetworkLoadBalancer
    Export:
      Name: vesta-nlb-arn

  NlbDns:
    Description: Network Load Balancer DNS Name
    Value: !GetAtt NetworkLoadBalancer.DNSName
    Export:
      Name: vesta-nlb-dns

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref NlbTargetGroup
    Export:
      Name: vesta-tg-arn

  ApiId:
    Description: API Gateway ID
    Value: !Ref RestApi
    Export:
      Name: Vesta-RestApiId
  
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  clusterName:
    Value: !Ref EcsCluster
    Export:
      Name: vesta-ecs-cluster

  ServiceName:
    Value: !GetAtt EcsService.Name
    Export:
      Name: vesta-ecs-service