AWSTemplateFormatVersion: '2010-09-09'
Description: Internal NLB + API Gateway + VPC Link

Resources:

  #####################################
  # Network Load Balancer
  #####################################

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: vesta-internal-nlb
      Type: network
      Scheme: internal
      Subnets:
        - !ImportValue subnet1a-id
        - !ImportValue subnet1c-id
        - !ImportValue subnet1d-id

  NlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: vesta-tg
      TargetType: ip
      Protocol: TCP
      Port: 80
      VpcId: !ImportValue vpc1-id
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port

  NlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Protocol: TCP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroup

  #####################################
  # API Gateway VPC Link
  #####################################

  ApiGatewayVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: my-vpc-link
      TargetArns:
        - !Ref NetworkLoadBalancer

  #####################################
  # REST API
  #####################################

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyRestApi

  #####################################
  # Proxy Resource
  #####################################

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: '{proxy+}'

  #####################################
  # Proxy Method
  #####################################

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiResource
      HttpMethod: ANY

      AuthorizationType: NONE

      RequestParameters:
        method.request.path.proxy: true

      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET

        Uri:
          Fn::Sub:
            - 'http://${NlbDnsName}/{proxy}'
            - NlbDnsName: !GetAtt NetworkLoadBalancer.DNSName

        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink

        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'

  #####################################
  # Deployment
  #####################################

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiMethod
    Properties:
      RestApiId: !Ref RestApi

  #####################################
  # Stage
  #####################################

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod

  #####################################
  # API Gateway CloudWatch Logs
  #####################################

  ApiAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: apigateway-cloudwatch-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

Outputs:

  NlbArn:
    Description: Network Load Balancer ARN
    Value: !Ref NetworkLoadBalancer
    Export:
      Name: vesta-nlb-arn

  NlbDns:
    Description: Network Load Balancer DNS Name
    Value: !GetAtt NetworkLoadBalancer.DNSName
    Export:
      Name: vesta-nlb-dns

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref NlbTargetGroup
    Export:
      Name: vesta-tg-arn

  ApiId:
    Description: API Gateway ID
    Value: !Ref RestApi
    Export:
      Name: Vesta-RestApiId

  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"